# requirements.yaml
dependencies:
- name: jupyterhub
  version: "jupyterhub-0.9.0-beta.3"
  repository: 'https://jupyterhub.github.io/helm-chart/'
  import-values:
    - child: rbac
      parent: rbac
- name: mysql
  version: "1.4.0"
  repository: '@stable'

